apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tasks-hpa 
spec:
  scaleTargetRef:
    kind: DeploymentConfig 
    name: tasks-dc 
    apiVersion: apps/v1 
    subresource: scale
  minReplicas: 1 
  maxReplicas: 10 
  cpuUtilization:
    targetCPUUtilizationPercentage: 80 
